### ISSUE TITLE
Hyprpaper can't found file with socat but can with hyprctl

### ISSUE THREAD

**Issue by cylian914** [hyprwm/hyprpaper#101]
hi, i am trying to make [variety](https://github.com/cylian914/variety) support hyprpaper but i don't  want to only make it support only hyprland so i can't use hyprctl.

When using socat it seem hyprpaper's preload function can't found the wallpaper but can when using it with the exact same argument with hyprctl hyprpaper, i even made a bash script so i am sure i don't do any error.
here the simple bash script:
```bash
WP=/home/cylian91/.config/variety/wp/burningflag.jpg
hyprctl hyprpaper preload $WP
sleep 10 # wait just in case
echo             "preload $WP" | socat - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.hyprpaper.sock
```
the script return 
```
ok
preload failed (no such file)
```

**Comment by cylian914** [comment]
it look like socat add these:
```
[LOG] char 57: 32
[LOG] char 58: 92
[LOG] char 59: 110
[LOG] char 60: 10
```

**Comment by vaxerski** [comment]
might be an issue with socat then no?

If you don't wanna use hyprctl, why not connect to the socket via normal, plain old C, or whatever programming language you use?

**Comment by cylian914** [comment]
yes its an issue wit socat and not hyprland, the issue can be closed
