### ISSUE TITLE
Fractional Unit Error

### ISSUE THREAD

**Issue by Stella-Zephyr** [hyprwm/hyprpaper#103]
## Error 0: Fractional scale exists

After some updates to my laptop, this started showing up when starting Hyprpaper. I can confirm it's happening for hyprpaper and hyprpaper-git.

[LOG] Welcome to hyprpaper!
built from commit d6856adaffb77a9cc1aac3d04d98276eaa5602a4 (?)
[LOG] Cleaned old hyprpaper preloads (9), removing 74.6MB
[LOG] Preloaded target /home/estela-bv/.local/share/wallpapers/Mountains.jpg in 17.12ms -> Pixel size: [1920, 1080]
[LOG] Preloaded target /home/estela-bv/Imágenes/TransAsteroidBelt.png in 89.05ms -> Pixel size: [1920, 1200]
[LOG] Preloaded target /home/estela-bv/Imágenes/Suntrees.jpg in 16.64ms -> Pixel size: [1920, 1080]
[LOG] Preloaded target /home/estela-bv/Imágenes/my-neighbor-totoro-sunflowers.png in 31.06ms -> Pixel size: [1920, 1080]
[LOG] Preloaded target /home/estela-bv/Imágenes/CelesteEndGame.png in 25.93ms -> Pixel size: [1920, 1080]
[LOG] Preloaded target /home/estela-bv/Imágenes/Clearnight.jpg in 164.45ms -> Pixel size: [5760, 3240]
[LOG] hyprpaper socket started at /tmp/hypr/9d2a5fb41752c0dcc8e863d7e98b541656584dd9_1699041114/.hyprpaper.sock (fd: 4)
[LOG] Buffer created for target /home/estela-bv/Imágenes/Clearnight.jpg, Shared Memory usage: 8.3MB
[LOG] Buffer created for target /home/estela-bv/Imágenes/CelesteEndGame.png, Shared Memory usage: 8.3MB
[LOG] Buffer created for target /home/estela-bv/Imágenes/Suntrees.jpg, Shared Memory usage: 8.3MB
[LOG] Buffer created for target /home/estela-bv/Imágenes/TransAsteroidBelt.png, Shared Memory usage: 8.3MB
[LOG] Buffer created for target /home/estela-bv/Imágenes/my-neighbor-totoro-sunflowers.png, Shared Memory usage: 8.3MB
[LOG] Buffer created for target /home/estela-bv/.local/share/wallpapers/Mountains.jpg, Shared Memory usage: 8.3MB
[LOG] Total SM usage for all buffers: 49.8MB
wp_fractional_scale_manager_v1@8: error 0: Fractional scale exists.

After this, hyprpaper quits. 

![imagen](https://github.com/hyprwm/hyprpaper/assets/149267509/aa245381-5352-45d0-8035-8f70bf4875bf)

**Comment by vaxerski** [comment]
oops oops https://github.com/hyprwm/Hyprland/commit/21ba8b363e94294c3af8ac535728d5ad27762d35

**Comment by Stella-Zephyr** [comment]
Confirming the bug is solved, thank you!
