### ISSUE TITLE
flickering hyprland mascot wallpaper on startup

### ISSUE THREAD

**Issue by kulothunganug** [hyprwm/hyprpaper#105]
when i freshly loggin in to a hyprland session
hyprland's mascot wallpaper (default) appears for 1-2 seconds
and then my wallpaper appears which is I set from the config file

is it a bug or it's just taking some time to load my wallpaper (it is 10MB size), if so how can i to tackle it?

**Comment by vaxerski** [comment]
not a bug, just loading the wallpaper. You can disable the hyprland default background in the hyprland config, which will make it a black background instead.
