### ISSUE TITLE
Launch aborting with logic_error

### ISSUE THREAD

**Issue by BabyMephi** [hyprwm/hyprpaper#107]
After reinstalling hyprpaper on arch using cmake I have encountered this error:

`[LOG] Welcome to hyprpaper!
built from commit 38e18b70777be4e8af45698b8c7bdbf3a04387a0 (?)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
Aborted`

This happens when running ./hyprpaper as sudo. I previously had hyprpaper installed through pacman, however that would give me the exact same issue when running as sudo. If I run without sudo, I of course get an error with /home/USER/.config/ not existing as it doesn't have the privileges to access the folder. I'm not sure what exactly I'm doing wrong. I've attempted to look around to see what other people have done to fix this issue but nothing I've seen so far has helped.

**Comment by vaxerski** [comment]
dont sudo and fix your permissions

**Comment by BabyMephi** [comment]
> dont sudo and fix your permissions

I had a look at this briefly before realising I just hadn't created a config file, so I quickly wrote one out and it works fine now.
