### ISSUE TITLE
Configfile should be optional

### ISSUE THREAD

**Issue by tbaumann** [hyprwm/hyprpaper#109]
I like to select random wallpapers from a directory.

`wpaprd` can do that and has a nice CLI to cycle through. But loading the images is really slow.

Using `hyprpaper` I can implement that via external scripts.

- preload the next random wallpaper
- wait N minutes
- set that preloaded  wallpaper, unload the old one and preload the next one.
- repeat
- Make that script listen to signals to control it (next command)

Annoyingly `hyprpaper`  refuses to start unless I provide a config-file with a hard-coded wallpaper.

It's not the end of the world. And I suppose it's not a bad idea to launch with some kind of small static splash wallpaper. 

But considering that everything else can be done via IPC I wonder if it's really necessary to require a config file.

**Comment by tbaumann** [comment]
PS: It would be cool if `hyprpaper` implemented a random non-repeating carousel of pictures from a directory internally.
Controllable via IPC (prev, next, get-current)

**Comment by keithbowes** [comment]
What is this wpaprd of which you speak (searching the web only comes up with this issue)?

Yeah, it is pretty weird that without a config file, I get an error, but with an empty config file, it starts up fine and then I can use IPC to set the background at run time; that is, at least with v0.5.0, the config file needs to exist but doesn't have to contain a hard-coded wallpaper.

**Comment by tbaumann** [comment]
Sorry for the typo. That's https://github.com/danyspin97/wpaperd

Empty file, interesting tip.
