### ISSUE TITLE
hyprpaper crashes when no wallpaper path specified

### ISSUE THREAD

**Issue by E15dev** [hyprwm/hyprpaper#115]
doing `hyprctl hyprpaper wallpaper ,` or just not specifying wallpaper path make hyprpaper wait few seconds and then crash. i think it should  say 'wallpaper failed (syntax)' or something like that instead. logs are
```
[LOG] Accepted incoming socket connection request on fd 5
[LOG] Received a request: wallpaper ,
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 0)
```

**Comment by E15dev** [comment]
i think its line 132 from src/config/ConfigManager.cpp

**Comment by tobiichi3227** [comment]
@E15dev Please close this issues.
I fixed this problem.
But my commit didn't close this issues.
Sorry.

**Comment by E15dev** [comment]
nice, also sorry i didnt realized there was issue for it already
