### ISSUE TITLE
Hyprpaper IPC: Wallpaper all monitors

### ISSUE THREAD

**Issue by plurpio** [hyprwm/hyprpaper#122]
Currently in the Hyprpaper configuration using the following line would set your wallpaper for all monitors.

`wallpaper = ,/path/to/image.png`

However when doing the same using IPC it fails silently, giving an OK.

![image](https://github.com/hyprwm/hyprpaper/assets/148961679/0c5b2f4e-edf3-4b69-8f34-f563d77d5cef)
(the wallpaper didn't change but IPC gave an OK)

**Expected Behaviour**

The wallpaper for all monitors should of changed but no wallpapers changed at all.

**Comment by anufrievroman** [comment]
I have the same problem even now:

![image](https://github.com/hyprwm/hyprpaper/assets/42904990/29a0b188-6ee5-4f21-8a74-10bd19494a43)

Hyprland 0.40
hyprpaper 0.7
