### ISSUE TITLE
How to use without hyprpaper.conf

### ISSUE THREAD

**Issue by Jeffser** [hyprwm/hyprpaper#125]
Hi I saw that the latest release has these notes
- hyprpaper now uses hyprlang for config parsing
- A config file is no longer required

I was wondering how this works, where should I configure it now and how? thanks

**Comment by vaxerski** [comment]
If you use the config it's just like it was.

If you don't want to use a config, you can do everything via IPC, e.g. `hyprctl hyprpaper preload <path> && hyprctl hyprpaper wallpaper ,<path>`

**Comment by nnyyxxxx** [comment]
> If you use the config it's just like it was.
> 
> If you don't want to use a config, you can do everything via IPC, e.g. `hyprctl hyprpaper preload <path> && hyprctl hyprpaper wallpaper ,<path>`

oh wow nice, finally!

**Comment by nnyyxxxx** [comment]
nvm im tripping this is from 2024
