### ISSUE TITLE
Hyprland Initialization: Unveiling the Default Wallpaper and Swift Transition to Hyprpaper Settings

### ISSUE THREAD

**Issue by DU4NEL** [hyprwm/hyprpaper#133]
When I start Hyprland it shows me for a few moments the default wallpaper next to the splash and then loads the configuration I have in hyprpaper changing the wallpaper for a custom one and removing the splash.

**Comment by vaxerski** [comment]
that is correct

**Comment by xiaodong2077** [comment]
Wallpapers 
The “Hyprland” background you see when you first start Hyprland is NOT A WALLPAPER, it’s the default image rendered at the bottom of the render stack.

https://wiki.hyprland.org/Configuring/Keywords/#wallpapers
