### ISSUE TITLE
[Feature request] Single color wallpaper

### ISSUE THREAD

**Issue by o0nd7ots** [hyprwm/hyprpaper#135]
I am running a secondary OLED screen and on Plasma I always changed the wallpaper to black.
On hyprpaper, as far as I know, the only way to do this is by using a `black.jpg` or something of sorts.

Allowing users to declare single-color wallpapers would be a nice feature. 
What do you think?

**Comment by fufexan** [comment]
See `misc:background_color` in the wiki https://wiki.hyprland.org/Configuring/Variables/.
