### ISSUE TITLE
Cannot open shared object file

### ISSUE THREAD

**Issue by nyx6965** [hyprwm/hyprpaper#140]
I am getting this error after I installed `hyprlang-git` ,`hyprlock-git` & `hyprpaper-git` using AUR

`hyprpaper: error while loading shared libraries: libhyprlang.so.0: cannot open shared object file: No such file or directory`

I have tried finding the file and it exists
`mertens@nyxarch:~/Desktop$ sudo find / -iname libhyprlang.so
/usr/lib/libhyprlang.so
`
and also I did
`sudo ldconfig`

**Comment by vaxerski** [comment]
libhyprlang is at sover `1` not `0`, consider recompiling your git packages (or install them from source, they might be outdated)
