### ISSUE TITLE
Nothing happen when running hyprctl hyprpaper [Any command! (listactive, listloaded ...)]

### ISSUE THREAD

**Issue by L1xus** [hyprwm/hyprpaper#142]
I installed hyprpaper on arch using this command `sudo pacman -S hyprpaper`
I did what's in the README and indeed the wallpaper changes to what I set in the conf
but when I use any of the commands `hyprctl hyprpaper listloaded` or `hyprctl hyprpaper listloaded` I get an `Invalid Command` msg!!
When I also try to change the wallpaper
 `hyprctl hyprpaper preload [Path to img]` 
`hyprctl hyprpaper wallpaper ...` 
I only get ok msg without anything happen!

Any help on this issue please!
do I need to use a specific version?

**Comment by vaxerski** [comment]
listloaded and listactive are only available in git

**Comment by L1xus** [comment]
> listloaded and listactive are only available in git

how about changing wallpapers using hyprctl ....?

**Comment by vaxerski** [comment]
post your full command(s) and config

**Comment by L1xus** [comment]
I'm so sorry!
I figured out that I was using this command
`hyprctl hyprpaper wallpaper "DP-1,~/Wallpapers/gtr.jpg" `
instead of this 
`hyprctl hyprpaper wallpaper "eDP-1,~/Wallpapers/gtr.jpg" `

Thank you so much for your help!

**Comment by ser** [comment]
> listloaded and listactive are only available in git

please release it - it's time! :-)
