### ISSUE TITLE
Config error at line 1: Invalid config line

### ISSUE THREAD

**Issue by ZerdoX-x** [hyprwm/hyprpaper#149]
Config:
```
preload = /home/user/media/pictures/wallpaper/pic.png
wallpaper = eDP-1, /home/user/media/pictures/wallpaper/pic.png
ipc = off
```

Hyprpaper: `gui-apps/hyprpaper-0.6.0-r1`

Occurred after system upgrade.

Logs:
```
[LOG] Welcome to hyprpaper!
built from commit  ()
Error in config:
Config error at line 1: Invalid config line
[LOG] hyprpaper socket started at /tmp/hypr/<id>/.hyprpaper.sock (fd: 4)
[WARN] Monitor eDP-1 does not have a target! A wallpaper will not be created.
```

**Comment by vaxerski** [comment]
No clue what distro you're using, that would be convenient to point out.

Wild guess: possible that you updated hyprlang, which had an ABI break, without recompiling hyprpaper afterwards.

**Comment by ZerdoX-x** [comment]
> Wild guess: possible that you updated hyprlang, which had an ABI break, without recompiling hyprpaper afterwards.

Seems like it. I recompiled both hyprlang and hyprpaper, all works fine now. Probably fault of gentoo packages not correctly marking dependencies
