### ISSUE TITLE
hyprpaper cannot load libhyprlang.so.1 with hyprlang-git

### ISSUE THREAD

**Issue by kabeleh** [hyprwm/hyprpaper#151]
I switched to `hyprlang-git`, to update `hyprland-git`, but it broke `hyprpaper-git`:
```
❯ hyprpaper
hyprpaper: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory
```
I know something similar was an issue some weeks ago when the arch mirrors weren't up-to-date. But here, I'm on the `git` versions, and `hyprlang` should be present as expected in version `libhyprlang.so=1-64` as required by `hyprpaper`. Which crucial step am I missing?

Thank you for your time and effort. Please let me know which kind of logs or further information are required.

Installed versions:
`hyprpaper-git-0.6.0.r12.g518adca-1`
`hyprlang-git-0.5.0.r0.a685493-1`

**Comment by vaxerski** [comment]
recompile

**Comment by dotaxis** [comment]
Recompile what? These are aur packages that should be compiling straight from this repo.

**Comment by dotaxis** [comment]
Yeah this is not fixed for me. Not sure why issue was closed.

I ran `paru -S hyprpaper-git hyprland-git hyprlang-git --rebuild`

And still get `hyprpaper: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory`

**Comment by vaxerski** [comment]
you need to rebuild deps after updating hyprlang. Anyways, this is not an issue with hyprpaper, it's an issue with your system, that's why it was closed

**Comment by dotaxis** [comment]
Okay, but clearly this was caused by some sort of change that I did not make since I was forced to switch to hyprlang-git to stay up to date. Why leave a single word answer and commit to not helping any further? Rebuilding the packages did not work on my machine, what else am I supposed to do to get it working?

**Comment by vaxerski** [comment]
because this is not a problem with my code. sorry but I do not have telepathic abilities to enter your computer and find what's wrong. You clearly have a hyprpaper compiled against an outdated version of hyprlang that's not present on your system anymore.

**Comment by dotaxis** [comment]
> because this is not a problem with my code

Fair.

Something very strange was going on with my paru installation. Not really sure what. Sorry for dragging this out
