### ISSUE TITLE
Monitor eDP-1 does not have a target! A wallpaper will not be created.

### ISSUE THREAD

**Issue by grszik** [hyprwm/hyprpaper#154]
Hello, I've been using hyprpaper for some time now and suddenly when I plugged my second monitor (for the first time) the wallpaper stopped displaying and when running `hyprpaper` in console i was just getting two warnings:
```
[WARN] Monitor eDP-1 does not have a target! A wallpaper will not be created.
[WARN] Monitor DP-2 does not have a target! A wallpaper will not be created.
```
From this time on, the wallpaper is not displaying with the first warning, since I'm not using the second monitor. My config: 
```
preload = ~/WALL.png
wallpaper = eDP-1,~/WALL.png
wallpaper = DP-2,~/WALL.png
```
What's interesting is that if I set the wallpaper and preload with hyprctl it works just fine. I'm using those commands: 
```
hyprctl hyprpaper preload ~/WALL.png
hyprctl hyprpaper wallpaper eDP-1,~/WALL.png
```
The entire thing that shows when running `hyprpaper`: 
```
[LOG] Welcome to hyprpaper!
built from commit  ()
[LOG] Using config location /home/grosik/.config/hypr/hyprpaper.conf.
Error in config:
Config error at line 1: Invalid config line
[LOG] hyprpaper socket started at /tmp/hypr/1c460e98f870676b15871fe4e5bfeb1a32a3d6d8_1711471715/.hyprpaper.sock (fd: 4)
[WARN] Monitor eDP-1 does not have a target! A wallpaper will not be created.
```

**Comment by vaxerski** [comment]
update hyprlang and hyprpaper

**Comment by CrossScarDev** [comment]
I just got an external monitor, and I'm having the same issue. I've tried with the latest version of all the hypr packages in the arch repo and the AUR git packages.
