### ISSUE TITLE
hyprctl command doesn't change the wallpaper

### ISSUE THREAD

**Issue by mylinuxforwork** [hyprwm/hyprpaper#157]
Hi,
Just checking out hyprpaper as an alternative to swww for my dotfiles.

Installed hyprpaper with sudo pacman -S hyprpaper

Setting up a wallpaper via hyprpaper.conf was successful.

```
preload = ~/wallpaper/hyprland.jpg
wallpaper = ,~/wallpaper/hyprland.jpg
```

Now, I want to change the wallpaper with hyprctl

```
#!/bin/bash
hyprctl hyprpaper preload "~/wallpaper/cyber.jpg"
hyprctl hyprpaper wallpaper ",~/wallpaper/cyber.jpg"
```

See two "OK" in the terminal but the wallpaper is not changing.

Any ideas?

Thanks a lot in advance.

**Comment by vaxerski** [comment]
I believe this is fixed in git.

**Comment by mylinuxforwork** [comment]
Will wait until the feature is available in pacman.
I'm using the killall hyprpaper, update hyprpaper.conf, hyprpaper & workaround for now (which is working fine).

Thanks.

**Comment by Rabcor** [comment]
> I believe this is fixed in git.

Can confirm, fixed in git.
