### ISSUE TITLE
Screen bugs when disabling monitor

### ISSUE THREAD

**Issue by AlvaroParker** [hyprwm/hyprpaper#158]
I'm experiencing a bug when turning of my built in monitor:

![Screenshot-2024-03-30_16:27:30](https://github.com/hyprwm/hyprpaper/assets/64918109/b65d0be1-e976-4fe5-ae19-5b2ea789358c)

Steps to reproduce: 
- Log into hyprland with both monitors enabled
- Execute `hyprpaper` on the terminal
- Turn off built in monitor and move external monitor to `(0, 0)`: `hyprctl keyword monitor eDP-1, disable && hyprctl keyword monitor HDMI-A-1, 1920x1080, 0x0, 1`

If I stop `hyprpaper` and launch it again, the error is gone. 

Distribution: Arch Linux
Package: `extra/hyprpaper 0.6.0-4`

**Comment by vaxerski** [comment]
are you on hyprland-git? this was a bug in git that was fixed

**Comment by AlvaroParker** [comment]
@vaxerski No, I was on `hyprland` but I've installed `hyprland-git` and can confirm that the issue is gone
