### ISSUE TITLE
Option to configure the color and font of splash text

### ISSUE THREAD

**Issue by mooncoffee1** [hyprwm/hyprpaper#159]
on the deafult hyprland wallpaper you can do that with 

  col.splash = 0xffffffff
   splash_font_family = Iosevka

into the misc section. but here on hyprpaper there its not an option. Please some1 who can do it, pls do it i beg u

**Comment by v411e** [comment]
Might be a duplicate of #146

**Comment by mooncoffee1** [comment]
no new news about splash font family ? it would really be cool to be able to do that as default wallpaper
