### ISSUE TITLE
Missing dependency in manual build/installation in Fedora

### ISSUE THREAD

**Issue by ImanolFotia** [hyprwm/hyprpaper#161]
In the manual installation section for Fedora, the development package for hyprlang (`hyprlang-devel`) is missing, and cmake will complain about it.  

Running `sudo dnf install hyprlang-devel` fixes the issue.  

The package should be added to the previous dep. command installation

**Comment by vaxerski** [comment]
MRs welcome, I don't use fedora and can't really assert validity
