### ISSUE TITLE
[Feature Request] GIF Support

### ISSUE THREAD

**Issue by Rabcor** [hyprwm/hyprpaper#165]
If you try to load a GIF:
`[CRITICAL] unrecognized image /path/to/image.gif`

It would be really cool if you could load gifs, particularly animated gifs with hyprpaper. I don't know how feasible it really is, but I know swww can do it, it also supports webp, but I'd love to have the option.

On the note of webp (probably deserves it's own issue) trying to load an animated webp on hyprpaper gives me this.
`[CRITICAL] createSurfaceFromWEBP: WebP Decode Failed (?)`

Static webp works tho.

**Comment by vaxerski** [comment]
No animations are supported or even planned. #127

**Comment by Rabcor** [comment]
Sadness

**Comment by datdadev** [comment]
Ha, bruh, alright
