### ISSUE TITLE
XCURSOR_SIZE doesn't affect the cursor hovering over the wallpaper

### ISSUE THREAD

**Issue by danielgafni** [hyprwm/hyprpaper#17]
The title

**Comment by vaxerski** [comment]
[patch.txt](https://github.com/hyprwm/hyprpaper/files/10042114/patch.txt)

Can you check this patch out?

Copy to the source, and do `patch -p1 < ./patch.txt`, then compile

**Comment by danielgafni** [comment]
nope it doesn't work

What I did:

```shell
git clone git@github.com:hyprwm/hyprpaper.git
cd hyprpaper
patch -p1 < ~/Downloads/patch.txt
make all
# kill existing hyprpaper process
XCURSOR_SIZE=64 ./build/hyprpaper
```

**Comment by vaxerski** [comment]
Fixed. You'll need to recompile hyprland too because of [250d61e0b3e23ed7088dd7a309b3a5b3a2d6577c](https://github.com/hyprwm/Hyprland/commit/250d61e0b3e23ed7088dd7a309b3a5b3a2d6577c)

**Comment by danielgafni** [comment]
Thanks! I'll have to wait for the `hyprland-nvidia-git` package to update tho.

**Comment by vaxerski** [comment]
-git packages do not push an update to you. You need to manually `yay -S hyprland-nvidia-git` and select `CleanBuild`

**Comment by danielgafni** [comment]
Wow it works! Thanks again :heart: !
