### ISSUE TITLE
Socket missing.

### ISSUE THREAD

**Issue by YaroKasear** [hyprwm/hyprpaper#170]
It seems like hyprctl hyprpaper isn't working. 

Despite the fact hyprpaper is running, I get this:

```console
Couldn't connect to /run/user/1000/hypr/_1715171536_207074319/.hyprpaper.sock. (3)
```

I checked and the socket is not there. I don't know where hyprpaper is putting it, but it's not being put where it's supposed to be. I even looked in /tmp on the off chance hyprpaper might still be trying to set up a socket in the old location, but there's no /tmp/hypr there. 

I'm up to date on Nix with the flake. 

I ran hyprpaper from a terminal and here's my output:

```console
[LOG] Welcome to hyprpaper!
built from commit v0.6.0 ()
[LOG] Cleaned old hyprpaper preloads (1), removing 14.7MB
[LOG] Preloaded target /nix/store/dz91chvcrp5358y86xf637dxmybv6aqm-maze.png in 3.32ms -> Pixel size: [500, 500]
[LOG] hyprpaper socket started at /tmp/hypr/_1715171536_207074319/.hyprpaper.sock (fd: 4)
[ERR] Couldn't listen on the hyprpaper Socket. (3) IPC will not work.
[LOG] Buffer created for target /nix/store/dz91chvcrp5358y86xf637dxmybv6aqm-maze.png, Shared Memory usage: 14.7MB
[LOG] Total SM usage for all buffers: 14.7MB
[LOG] configure for DP-3
[LOG] handlePreferredScale: 1.00 for 160eda0
[LOG] handlePreferredScale: 1.00 for 160eda0
[LOG] Image data for DP-3: /nix/store/dz91chvcrp5358y86xf637dxmybv6aqm-maze.png at [0.00, -109.38], scale: 5.12 (original image size: [500, 500])
[LOG] Submitting viewport dest size 2560x1440 for 160eda0
[LOG] configure for DP-3
[LOG] handlePreferredScale: 1.00 for 160eda0
[LOG] handlePreferredScale: 1.00 for 160eda0
[LOG] Image data for DP-3: /nix/store/dz91chvcrp5358y86xf637dxmybv6aqm-maze.png at [0.00, -109.38], scale: 5.12 (original image size: [500, 500])
[LOG] Submitting viewport dest size 2560x1440 for 160eda0
[LOG] handlePreferredScale: 1.00 for 160eda0
```

Looks like maybe the Nix flake is outdated?

**Comment by vaxerski** [comment]
if you update hyprpaper to 0.6.0 you need to update hyprland to at least 0.40.0

**Comment by YaroKasear** [comment]
> if you update hyprpaper to 0.6.0 you need to update hyprland to at least 0.40.0 for the socket to work

I am running Hyprland 4.0. hyprctl doesn't show that, but a look at what is installed by Nix does:

```console
ls -l `which Hyprland`
lrwxrwxrwx - root 31 Dec  1969  /home/yaro/.nix-profile/bin/Hyprland -> /nix/store/2iwrx31j8vwxm7vnb9pvlhx5s2xl7ypv-**hyprland-0.40.0**+date=2024-05-08_36d3297/bin/Hyprland
```

```console
[LOG] Welcome to hyprpaper!
built from commit **v0.6.0** ()
```

**Comment by vaxerski** [comment]
then @fufexan for nix. My guess is `$XDG_RUNTIME_DIR` is not `/run/user/xyz`, in which case that was fixed in a commit a bit later, you can install hyprpaper git to verify that

**Comment by YaroKasear** [comment]
> then @fufexan for nix. My guess is `$XDG_RUNTIME_DIR` is not `/run/user/xyz`, in which case that was fixed in a commit a bit later, you can install hyprpaper git to verify that

```console
echo $XDG_RUNTIME_DIR               
/run/user/1000
```

Not that I mean come off as rude, but I think this would be more productive if I'm asked versions and values of environment variables rather than presuming what they are.

I'll see about installing the git version using the Flake, as I suspect I have the nixpkgs version.

**Comment by vaxerski** [comment]
then idk what's up and I'll wait for fufexan to say something, as nix has the weirdest issues with the filesystem structure.

Oh, wait, I misread the logs. Yes, you have hyprland 0.40.0, but hyprpaper is < 0.6.0. Update hyprpaper and it should work. You can see it's trying to connect to the _old_, pre-0.40 socket path:
![image](https://github.com/hyprwm/hyprpaper/assets/43317083/e9fbce7a-10eb-4239-ab7b-e24132bf709a)

**Comment by YaroKasear** [comment]
> then idk what's up and I'll wait for fufexan to say something, as nix has the weirdest issues with the filesystem structure.
> 
> Oh, wait, I misread the logs. Yes, you have hyprland 0.40.0, but hyprpaper is < 0.7.0. Update hyprpaper and it should work. You can see it's trying to connect to the _old_, pre-0.40 socket path: ![image](https://private-user-images.githubusercontent.com/43317083/329018508-e9fbce7a-10eb-4239-ab7b-e24132bf709a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxOTc4NDMsIm5iZiI6MTcxNTE5NzU0MywicGF0aCI6Ii80MzMxNzA4My8zMjkwMTg1MDgtZTlmYmNlN2EtMTBlYi00MjM5LWFiN2ItZTI0MTMyYmY3MDlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE5NDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzJmYTFhY2JlMjUzMDhhYmQzYWY3MjA3MjlmMWE3MTNkM2UxNWUxMmNhM2ZlNTgzYjU5Mzg4MTY3N2NhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lVOpYGY8hLd_YFA8PfsaxPOnAUpUhsamCg_mZuuHB9U)

Yes, I had seen that it was looking in /tmp/hypr and not in $XDG_RUNTIME_DIR. The requirement is .7 and not .6? 

Anyway, I built the git version through the Nix Flake and it's working now.

My fault for mixing the nixpkgs-unstable version of Hyprpaper with git Hyprland. I should settle on one or the other.

**Comment by vaxerski** [comment]
yea I made a mistake. 0.7 + 0.40.
