### ISSUE TITLE
Wallpaper not being set on all monitors after specific monitor wallpaper is set

### ISSUE THREAD

**Issue by nikolaizombie1** [hyprwm/hyprpaper#176]
I found an edge case where if you are using `hyprctl hyprpaper` to set wallpapers: The following behavior occurs with these steps:

1.  Turn on `hyprpaper` in the terminal
2. Unload all wallpapers using `hyprctl hyprpaper unload all`
3. Preload wallpaper using `hyprctl hyprpaper preload WALLPAPER`
4. Set wallpaper on all monitors using `hyprctl hyprpaper wallpaper ,WALLPAPER`
5. Unload all wallpapers using `hyprctl hyprpaper unload all`
6. Preload wallpaper using `hyprctl hyprpaper preload OTHER_WALLPAPER`
7. Set  wallpaper to a specific monitor using `hyprctl hyprpaper wallpaper MONITOR,OTHER_WALLPAPER`
8. Unload all wallpapers using `hyprctl hyprpaper unload all`
9. Preload wallpaper using `hyprctl hyprpaper preload ANOTHER_WALLPAPER`
10. Set wallpaper on all monitors using `hyprctl hyprpaper wallpaper ,ANOTHER_WALLPAPER`
11. The wallpaper is not changed on `MONITOR`

If I check the output of `hyprpaper` I can see that the image is being preloaded but it not being set for the monitor that was addressed individually. It changes for the monitors that were not addressed individually but not for the one(s) that were. Is this intended behavior?

**Comment by vaxerski** [comment]
this is indeed intended behavior. empty monitor means a fallback wildcard
![image](https://github.com/hyprwm/hyprpaper/assets/43317083/8b019c66-8dfe-4a48-9718-3cb648880220)

key part: _without a set wallpaper_

**Comment by nikolaizombie1** [comment]
> this is indeed intended behavior. empty monitor means a fallback wildcard ![image](https://private-user-images.githubusercontent.com/43317083/335681561-8b019c66-8dfe-4a48-9718-3cb648880220.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNzc0OTksIm5iZiI6MTcxNzE3NzE5OSwicGF0aCI6Ii80MzMxNzA4My8zMzU2ODE1NjEtOGIwMTljNjYtOGRmZS00YTQ4LTk3MTgtM2NiNjQ4ODgwMjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE3Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYzg0ZjJlYTBjNTk1MDcxNmRkMTU2YzNkMzNjN2QyMTRlMjkyYzIwMWQ1MTQxNjFhMzhlNGZiZDQ5NGY4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rnfuKsoIAhUsCBIDDVJgzzHtRAGXHq4VA5T7NlIXA4Q)
> 
> key part: _without a set wallpaper_

Oh OK then. Thank you for the quick reply.
