### ISSUE TITLE
weird wallpaper rotating

### ISSUE THREAD

**Issue by jjonojj** [hyprwm/hyprpaper#179]
When I want to set my wallpaper, it gets rotated by 180 degrees somehow. If I rotate it in Gwenview by 180 degrees and update the path in my hyprpaper.conf, it is **still** rotated by 180 degrees. I am very confused rn.

**Comment by vaxerski** [comment]
...._what_?

**Comment by jjonojj** [comment]
I have no idea lmao. I ended up choosing another wallpaper, as it only seemed to happen with a few specific images.
