### ISSUE TITLE
Crash when changing wallpaper

### ISSUE THREAD

**Issue by Roger-Roger-debug** [hyprwm/hyprpaper#18]
Now in the right project:

after commit [update wlroots dep](https://github.com/hyprwm/Hyprland/commit/23cd1b8c66da3e85692891e985567f6f45f6e501) hyprpaper crashes with `[destroyed object]: error -1: surface was destroyed before its role object` when trying to change the wallpaper. The initial wallpaper works fine.

**Comment by vaxerski** [comment]
fixed in 32e28312f14727f5d6aaedf3f7db5e282ec04df2
