### ISSUE TITLE
Error building on Ubuntu 24.04

### ISSUE THREAD

**Issue by vaskark** [hyprwm/hyprpaper#188]
Hi. I know I'm on a system that lags behind a bit but I was successfully building hyprpaper until a little while ago. This is the error:

```
Generating /home/vaskark/work/hyprpaper/protocols/tablet-v2.cpp, /home/jason/work/hyprpaper/protocols/tablet-v2.hpp
Couldn't load proto
gmake[3]: *** [CMakeFiles/hyprpaper.dir/build.make:123: /home/jason/work/hyprpaper/protocols/tablet-v2.cpp] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:82: CMakeFiles/hyprpaper.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:90: CMakeFiles/hyprpaper.dir/rule] Error 2
gmake: *** [Makefile:189: hyprpaper] Error 2
```

Can anyone offer some help with this?
Thanks

Ubuntu: 24.04
Hyprland: 0.41.2 (binary release)

**Comment by nobody5050** [comment]
+1

**Comment by nobody5050** [comment]
Some research has shown me the following:
- 24.04 ships with wayland-protocols 1.34.1
- hyprpaper needs wayland-protocols >=1.35 (1.35 introduces tablet v2)

**Comment by nobody5050** [comment]
commit d50f0eda6cb9be2a8419af21792195e54b285631 (which the latest release is based on) doesn't seem to require this and I was able to successfully build it on 24.04

**Comment by vaskark** [comment]
> commit [d50f0ed](https://github.com/hyprwm/hyprpaper/commit/d50f0eda6cb9be2a8419af21792195e54b285631) (which the latest release is based on) doesn't seem to require this and I was able to successfully build it on 24.04

I'm building hyprpaper from git. Should have mentioned that. Are you building from git?

**Comment by vaskark** [comment]
Okay, I installed wayland-protocols 1.36 and was able to build hyprpaper again.
Many thanks.
