### ISSUE TITLE
Couldn't connect to /run/user/1000/hypr/9a09eac79b85c846e3a865a9078a3f8ff65a9259_1723933735_988851351/.hyprpaper.sock. 

### ISSUE THREAD

**Issue by TmSalviano** [hyprwm/hyprpaper#192]
tiago@archlinux ~ % hyprpaper
[LOG] Welcome to hyprpaper!
built from commit  ()
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not find config in HOME, XDG_CONFIG_HOME, XDG_CONFIG_DIRS or /etc/hypr.
[1]    2477 IOT instruction (core dumped)  hyprpaper
134 tiago@archlinux ~ % hyprctl hyprpaper preload ~/Pictures/Wallpapers/JuliusCaesar.jpg
Couldn't connect to /run/user/1000/hypr/9a09eac79b85c846e3a865a9078a3f8ff65a9259_1723933735_988851351/.hyprpaper.sock. (3)

I've been looking for a solution for an hour now and I do not have time to fix my wallpaper for an hour.  Sorry if it is a silly problem that could've been fixed without resorting to this. Please notify me if more information is needed.

**Comment by vaxerski** [comment]
you dont have a hyprpaper config, thus it wont run

**Comment by TmSalviano** [comment]
Yep, you were right @vaxerski . I forgot to run a simple command such as: hyprpaper to know the answer, lmao! The weird thing is that hyprpaper related comands were working perfectly fine before and all of a sudden (probably after a package upgrade with yay) it stopped working, I guess that is the reason why I didn't even consider that the .config was missing. Thank you very much!
