### ISSUE TITLE
Changing screen's transform doesn't update the wallpaper

### ISSUE THREAD

**Issue by soufhehe** [hyprwm/hyprpaper#198]
https://github.com/user-attachments/assets/fd3fedf7-5469-4723-a248-48aff9ad254c

When the screen is rotated, the wallpaper does not rotate. If the command is executed again, the wallpaper rotates as expected

**Comment by caffeine01** [comment]
Will this be fixed/support provided?

**Comment by vaxerski** [comment]
MRs welcome

**Comment by caffeine01** [comment]
> MRs welcome

ok if i find the time then sure

**Comment by caffeine01** [comment]
> MRs welcome

Will start working on this today hopefully.

**Comment by caffeine01** [comment]
@soufhehe @vaxerski fixed in #224

**Comment by caffeine01** [comment]
@vaxerski can be closed now unless you need this guys input on the changes

**Comment by soufhehe** [comment]
Thanks ! It works :)

**Comment by caffeine01** [comment]
WOOHOO my first real contribution to an open source project that isn't mine
