### ISSUE TITLE
Unloading after setting the wallpaper

### ISSUE THREAD

**Issue by Jacob3075** [hyprwm/hyprpaper#20]
I went through the readme and I found `consider unloading those that you no longer need` but I'm not sure what no longer needed means. Does it mean that once I set the wallpaper I can unload it

eg flow:

```bash
hyprctl hyprpaper preload ~/Pictures/myepicpng.png
hyprctl hyprpaper wallpaper DP-1,~/Pictures/myepicpng.png
hyprctl hyprpaper unload ~/Pictures/myepicpng.png
```

Will the above cause any issues?

**Comment by vaxerski** [comment]
shouldnt. Try it

**Comment by Jacob3075** [comment]
Yeah I tried it later, forgot to update.

If I execute them manually it seems fine, the wallpaper is still set, but if I run it as part of a script hyprpaper crashes.
I'm guessing it's because the image is unloaded before it actually gets set.

**Comment by Jacob3075** [comment]
Is there any way where we can have only one image loaded at a time, like a setting in the config or a flag that unloads the previous image when preloading a new one?

Cause in my use case I'm using an app called variety to set my wallpapers and it calls a script (with the path to the image) that checks the DE/WM and sets the wallpaper. I don't have access to the previous image in this case so something like this would be useful, or like #19 would also work ig.

**Comment by vaxerski** [comment]
unload all added in 3571e20b55da7921a47d4910204b40ab1701b5c4

Close if you wish.

**Comment by Wa1t5** [comment]
@Jacob3075  I wrote a script for using one wallpaper at a time #21

**Comment by Jacob3075** [comment]
@vaxerski I just checked the commit changes, shouldn't this be called in `handleUnload`
https://github.com/hyprwm/hyprpaper/blob/3571e20b55da7921a47d4910204b40ab1701b5c4/src/config/ConfigManager.cpp#L115

right now it's in `handleWallpaper` so the command it matches is `... wallpaper all` instead of `... unload all`

----

@Wa1t5 I checked script, it might work but I feel like there's better ways to it

**Comment by Wa1t5** [comment]
@Jacob3075 Yep, I updated it to use hyprctl, but I still need to commit, I'll do it tomorrow have to sleep now

**Comment by vaxerski** [comment]
@Jacob3075 my retardness. Fixed.

**Comment by Jacob3075** [comment]
Cool, thanks 👍👍
