### ISSUE TITLE
Disable Scaling

### ISSUE THREAD

**Issue by mike-lloyd03** [hyprwm/hyprpaper#200]
I have a new laptop with an unnecessarily high pixel density. As a result, I've set monitor scaling to 1.4 so I can actually read what's on the screen.

But my slick wallpaper is zoomed in too much now.

Is it possible to disable scaling similar to what is done with `xwayland.force_zero_scaling` just for Hyprpaper?

Thanks.

**Comment by vaxerski** [comment]
wdym zoomed in? that should not happen. Are you using contain?

**Comment by mike-lloyd03** [comment]
Weird. After closing my laptop lid and opening it again, the image is unzoomed. 

I have my scale factor at 1.4 and it looked like it was zooming in on the top left corner of the image by about 40%
