### ISSUE TITLE
Tile feature in documentation but doesn't work

### ISSUE THREAD

**Issue by desdic** [hyprwm/hyprpaper#210]
https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/

when trying to use `tile:` you get an error saying that the wallpaper doesn't exits

**Comment by vaxerski** [comment]
![image](https://github.com/user-attachments/assets/25eced0d-ab4a-45ed-b6d0-cff9f3520df3)

an exception was thrown: did not read the wiki
