### ISSUE TITLE
Doesn't start with systemd unit

### ISSUE THREAD

**Issue by blackxored** [hyprwm/hyprpaper#220]
First of all apologies as this is most likely lack of knowledge and misconfiguration, but hyprpaper is enabled through systemd (gets enabled via home-manager I think), and I'm looking at ~/.config/systemd/hyprpaper.service, it fails to start with uwsm because of `WAYLAND_DISPLAY` not being set. Might be related to the target being `graphical-target.pre`?

**Comment by fufexan** [comment]
Yes, it's a known problem in Home Manager. Here's a temporary fix until someone merges related PRs. https://github.com/nix-community/home-manager/issues/5899#issuecomment-2498226238

**Comment by blackxored** [comment]
Thank you, that should do it, hopefully the fixes include hyprpaper as well.
