### ISSUE TITLE
Building hyprpaper from flake fails on NixOS

### ISSUE THREAD

**Issue by MrSom3body** [hyprwm/hyprpaper#221]
Building `hyprpaper` from this repositories flake fails on NixOS because of the `hyprlang` version being outdated. Here is the [build failure](https://gist.github.com/MrSom3body/bc9aa72263e1bdf113cd549f89b637cf).

Maybe relevant parts of my nix configuration:
- [flake.nix](https://github.com/MrSom3body/dotfiles/blob/898d3db271805ca7b3a4a26b7dbda6b460243470/flake.nix#L126)
- [hyprpaper.nix](https://github.com/MrSom3body/dotfiles/blob/898d3db271805ca7b3a4a26b7dbda6b460243470/home/services/wayland/hyprpaper.nix#L10)

**Comment by vaxerski** [comment]
@fufexan

**Comment by caffeine01** [comment]
@MrSom3body does this build failure occur when doing nixos-rebuild?
If so, have you tried going to your flake directory and running "nix flake update"?

If not, and you are working within a nix develop environment then you need to run "nix flake update" inside the folder of the source where the flake is.

**Comment by MrSom3body** [comment]
Yes, I did update with `nix flake update` :)

**Comment by fufexan** [comment]
Try `nix build github:hyprwm/hyprpaper`. If that builds fine, it's a lockfile problem.

**Comment by fufexan** [comment]
Ah wait I just saw your flake. Hyprland doesn't have the new hyprlang iirc, so the override is what makes it not work. I'll update in a sec.

**Comment by caffeine01** [comment]
> Yes, I did update with `nix flake update` :)

(i am not an expert but i will try and help)

 okay, i also noticed in your flake you put:
 ```nix
     hyprpaper = {
      url = "github:hyprwm/hyprpaper";
      inputs = {
        hyprlang.follows = "hyprland/hyprlang";
        hyprutils.follows = "hyprland/hyprutils";
        nixpkgs.follows = "hyprland/nixpkgs";
        systems.follows = "hyprland/systems";
      };
    };
    ```
    setting the inputs like this seems quite redundant, i think its meant to be more like:
    ```nix
      hyprpaper.url = "github:hyprwm/hyprpaper";
    ```
    
    Because in the hyprpaper flake everything is defined to follow the git repo anyway.

**Comment by fufexan** [comment]
What those `follows` do is reuse hyprland's inputs in order not to duplicate dependencies. But the cost is that they have to be all in sync or we get build failures like this.

**Comment by caffeine01** [comment]
the mighty fufexan has spoken

**Comment by caffeine01** [comment]
> What those `follows` do is reuse hyprland's inputs in order not to duplicate dependencies. But the cost is that they have to be all in sync or we get build failures like this.

so was i right in suggesting that they just *don't redefine the inputs like that*?

**Comment by fufexan** [comment]
They do redefine the inputs, that's the point. It's entirely optional and you should only do this if you want to reduce evaluation time or save some space.

**Comment by caffeine01** [comment]
holy shit you already replied 4 minutes before me i didnt even see that my bad sorry

**Comment by fufexan** [comment]
Updated the dep chain, another flake update should get you going.

**Comment by MrSom3body** [comment]
I mean, it kinda works now. Hyprpaper build, but now hypridle seems to fail to build:
[hypridle.log](https://gist.github.com/MrSom3body/c0e9719b1abcd0e91287bc6f012235b2)

**Comment by MrSom3body** [comment]
Everything's able to update, thanks :)
