### ISSUE TITLE
Hyprpaper not setting to custom background

### ISSUE THREAD

**Issue by floatyHorizonOfficial** [hyprwm/hyprpaper#228]
I have spend a lot of time searching making many changes, but none make a difference.
In my ~/.config/hypr/hyprpaper.conf I have the following:
```
preload=/home/floaty/Pictures/BGs/DAWN.png
wallpaper=HDMI-A-1,/home/floaty/Pictures/BGs/DAWN.png
ipc=true
splash=true
```
In my hyprland.conf I do run `exec-once=hyprpaper &`. The default backgrounds do work, which might be something.

And I am unable to load the background manually through the terminal using hyprctl, instead just saying it cannot find the hyprpaper socket. (I haven't been able to fix this either)

**Comment by Irgendeinwer** [comment]
I think I have the same issue as @floatyHorizonOfficial 
When running `$ hyprctl hyprpaper`
I get this error:
`Couldn't connect to /run/user/1000/hypr/12f9a0d0b93f691d4d9923716557154d74777b0a_1734855552_75049431/.hyprpaper.sock. (3)
`
I also get an error when running hyprpaper directly: `$ hyprpaper`
```
[LOG] Rendering splash: %s
[LOG] Splash color: 55ffffff
[LOG] Splash font size: 28, pos: 1920.00, 2116.80
[LOG] Submitting viewport dest size 1920x1080 for d98b1b0
wl_display#1: error 0: invalid object 18
```

**Comment by floatyHorizonOfficial** [comment]
Tried disabling the splash, but nothing seems to have changed, still only gives me a grey screen as a background.
After looking through #225 it would appear their issue was Nix specific? Which might not help too much since I run Arch.
I did attempt to run hyprpaper directly too, but it'd appear I cannot run it as a command.

**Comment by floatyHorizonOfficial** [comment]
It would appear it works now after the latest update.
Still unsure what caused the issue, but with it gone I guess this isn't needed any longer.
