### ISSUE TITLE
wl_display#1: error 1: invalid arguments for wl_shm_pool#22.create_buffer

### ISSUE THREAD

**Issue by arminveres** [hyprwm/hyprpaper#229]
Hi there,
I am using bleeding edge NixOS unstable (25.05) with Hyprland flake and encountered an issue on a recent update (today). The background was not getting set which led me to `journalctl`.
There I found that hyprpaper crashed with the following error:
`wl_display#1: error 1: invalid arguments for wl_shm_pool#22.create_buffer`

**Comment by vaxerski** [comment]
is it perhaps the same as #225?

**Comment by arminveres** [comment]
Yep, disabling splash solved it...
