### ISSUE TITLE
Allow syntax for random preload.

### ISSUE THREAD

**Issue by Mikilio** [hyprwm/hyprpaper#27]
It would be nice to allow for random preloads by specifying a path like this

`preload = /path/to/wallpapers/{1}.png`

In that case, it would select a random .png from the folder "wallpapers" and store the filename in a register "{1}".
This way we can reference it later by:

`wallpaper = monitor, /path/to/wallpapers/{1}.png`
or 
`hyprctl hyprpaper unload = /path/to/wallpapers/{1}.png`

This was just a fleeting idea, so some improvements must be made. But in general, I think this feature would be a lovely addition to this project.

**Comment by vaxerski** [comment]
why when you can
```
#!/bin/bash
$wp=${find /my/dir/blah/blah -type f | shuf -n 1}
echo -ne "preload = $wp \n wallpaper = DP-1,$wp"
hyprpaper
```
(or `hyprctl hyprpaper ...` if it's running)

**Comment by Mikilio** [comment]
I better grab some coffee ...
