### ISSUE TITLE
[Feature Request] Splash text like default bg

### ISSUE THREAD

**Issue by Amanse** [hyprwm/hyprpaper#28]
Would be great to add custom splash text command so either hyprctl can be used or just a static string or custom script to get random text from somewhere else

**Comment by vaxerski** [comment]
you can use `hyprctl splash` to retrieve the current splash. Setting your own is and will not be a thing.

**Comment by Amanse** [comment]
i wanted to know if there was any way to show the splash on wallpaper like it does on default bg?

**Comment by vaxerski** [comment]
no

**Comment by vaxerski** [comment]
added in e95b8d59f393ee7428932ebcd6c09849ff619b83
