### ISSUE TITLE
Hyprpaper crash latest aur build

### ISSUE THREAD

**Issue by khaneliman** [hyprwm/hyprpaper#32]
Upgraded to hyprpaper-git-r73.1c19aa2 and get:

> hyprpaper: ../cairo/src/cairo-surface.c:955: cairo_surface_destroy: Assertion `CAIRO_REFERENCE_COUNT_HAS_REFERENCE (&surface->ref_count)' failed.

Downgrading to hyprpaper-git-r71.c68cc7b and it works again.

**Comment by Ziqi-Yang** [comment]
same problem

**Comment by yfaimisaka** [comment]
same
