### ISSUE TITLE
hyprpaper crashes when new monitor gets connected

### ISSUE THREAD

**Issue by duckduck1** [hyprwm/hyprpaper#34]
**Expected behavior**

Monitors display hyprpaper wallpaper when turned on

**Acutal behavior**

hyprpaper crashes (no wallpaper displayed from hyprpaper)

**Steps to reproduce**

1. Configure wallpaper for both monitors
2. Have one monitor turned off
3. Run hyprpaper
4. Turn on the other monitor
5. Observe hyprpaper crash

**Logs**

This is the output I get when running hyprpaper from CLI the moment I turn on the monitor:
`listener function for opcode 1 of zwlr_layer_surface_v1 is NULL`
`zsh: IOT instruction (core dumped)  hyprpaper`

**Client config**

- Arch Linux with hyprland
- hyprpaper-git AUR build (built from commit 50852e531987d20c432122fbec7f1f089bc2dc09)
- I'm using hyprland with dedicated workspaces set for both monitors if that matters

**Comment by MonstrousOgre** [comment]
Same issue but for me it's happening when I disconnect a monitor. Doesn't happen when I connect it

I'm getting the same log output

**Comment by vaxerski** [comment]
letting yall know I am unable to have multiple monitors until late january so if anyone wants to make a patch feel free!

**Comment by lucascoelho07** [comment]
mine happens after my monitor wakes from standby
I don't remember it happening with my old one

**Comment by vaxerski** [comment]
some dumb monitors / laptops physically disconnect the display when standby / sleep happens and reconnect it afterwards

**Comment by lucascoelho07** [comment]
just noticed that hyprland also goes to workspace two after waking up too
can it be ralated?

**Comment by duckduck1** [comment]
I do not use power saving measures other than turning the display off and on via the power button. But I think the whole disconnect-reconnect-thing is because of DisplayPort and how it is designed or implemented.

At least my monitors are connected via DP.

When I turn off the display, nothing happens to hyrpaper (or even hyprland). It is only when I turn on the display, that hyprpaper crashes (and hyprland visually restores workspaces).

@lucascoelho07 I do have the same workspace issue for hyprland, but with different workspaces. It probably depends on what is configured. I think it should be a separate issue for hyprland.

**Comment by MonstrousOgre** [comment]
Not sure if this is helpful, but I use HDMI and it only happens to me while disconnecting

**Comment by eduardhojbota** [comment]
I'm encountering the same issue when turning off and on the monitor on HDMI with hyprpaper-git r65.88d99f9-1.
Logs:
`user@pc> hyprpaper
[LOG] Welcome to hyprpaper!
built from commit 88d99f99546d3ba42ed40f9b371471b320423f63 (    fix compile)
[LOG] Cleaned old hyprpaper preloads (1), removing 84.9MB
[LOG] Preloaded target /home/user/images/wallpaper.jpeg in 478.05ms -> Pixel size: [5500, 2750]
[LOG] hyprpaper socket started at /tmp/hypr/cf4cbf972522e45b51a5215266f7ce0e361d693e_1674992356/.hyprpaper.sock (fd: 4)
[LOG] configure for HDMI-A-1
[LOG] Buffer created for target /home/user/images/wallpaper.jpeg, Shared Memory usage: 84.9MB
[LOG] Total SM usage for all buffers: 84.9MB
[LOG] Image data for HDMI-A-1: /home/user/images/wallpaper.jpeg at [-305.56, 0.00], scale: 1.26 (original image size: [5500, 2750])
[LOG] configure for HDMI-A-1
[LOG] Image data for HDMI-A-1: /home/user/images/wallpaper.jpeg at [-305.56, 0.00], scale: 1.26 (original image size: [5500, 2750])
# Monitor turned off
# Monitor turned on
listener function for opcode 1 of zwlr_layer_surface_v1 is NULL
fish: Job 1, 'hyprpaper' terminated by signal SIGABRT (Abort)
`

**Comment by vaxerski** [comment]
fixed in 1a147160cf6d9ab2f4d23e772176ffb1c9752868
