### ISSUE TITLE
Wallpaper fallback not implemented

### ISSUE THREAD

**Issue by g33kex** [hyprwm/hyprpaper#35]
According to the documentation, an empty monitor name will act as a fallback and set the wallpaper on all connected monitors: `Wallpaper will apply the wallpaper to the selected output (monitor is the monitor's name, easily can be retrieved with hyprctl monitors. You can leave it empty for a wildcard (aka fallback))`

This doesn't seem to be currently implemented. When using:
```
wallpaper=,~/wallpaper.png
```
The wallpaper does not appear on any of the connected monitors.

**Comment by vaxerski** [comment]
works for me...? can I get your entire config? how are you launching hyprpaper? are there multiple monitors, do you connect/remove any dynamically?

**Comment by g33kex** [comment]
My bad hyprpaper had just crashed when disconnecting the monitor. Probably related to #34.
