### ISSUE TITLE
libjpeg dependency on Fedora 37

### ISSUE THREAD

**Issue by Whipplash** [hyprwm/hyprpaper#36]
Installing Hyprland on Fedora 37. After making it down to the Wallpaper guide within the Hyprland wiki and trying to manually install hyprpaper, I noticed toward the end of the install I'd seen an error regarding libjpeg, however to my knowledge Fedora (by default) comes with a variant called libjpeg-turbo. Is there anything that could be done to include/account for that to fulfill the libjpeg dependency?:

 ➜  make all
make clear
make[1]: Entering directory '/home/matt/repos/hyprpaper'
rm -rf build
rm -f *.o *-protocol.h *-protocol.c
make[1]: Leaving directory '/home/matt/repos/hyprpaper'
make protocols
make[1]: Entering directory '/home/matt/repos/hyprpaper'
/usr/bin/wayland-scanner private-code \
	protocols/wlr-layer-shell-unstable-v1.xml wlr-layer-shell-unstable-v1-protocol.c
/usr/bin/wayland-scanner client-header \
	protocols/wlr-layer-shell-unstable-v1.xml wlr-layer-shell-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/local/include -I/usr/include/libdrm -I/usr/include/valgrind -I/usr/include/pixman-1     -c -o wlr-layer-shell-unstable-v1-protocol.o wlr-layer-shell-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.c
/usr/bin/wayland-scanner client-header \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/local/include -I/usr/include/libdrm -I/usr/include/valgrind -I/usr/include/pixman-1     -c -o xdg-shell-protocol.o xdg-shell-protocol.c
make[1]: Leaving directory '/home/matt/repos/hyprpaper'
make release
make[1]: Entering directory '/home/matt/repos/hyprpaper'
mkdir -p build && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -H./ -B./build -G Ninja
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring hyprpaper!
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for modules 'wayland-client;wayland-protocols;cairo;pango;pangocairo;libjpeg'
--   Package 'libjpeg', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:44 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/matt/repos/hyprpaper/build/CMakeFiles/CMakeOutput.log".
make[1]: *** [Makefile:40: release] Error 1
make[1]: Leaving directory '/home/matt/repos/hyprpaper'
make: *** [Makefile:50: all] Error 2

**Comment by vaxerski** [comment]
`libjpeg-turbo` is what you should have. Maybe fedora has some `devel` version of it for building stuff.

**Comment by doopath** [comment]
```libjpeg-turbo-devel``` is that missed dependency

**Comment by maxwelljens** [comment]
On Fedora 38, the error occurs even with `libjpeg-turbo-devel` present:

```
make clear
make[1]: Entering directory '/home/maxwellj/Development/hyprpaper'
rm -rf build
rm -f *.o *-protocol.h *-protocol.c
make[1]: Leaving directory '/home/maxwellj/Development/hyprpaper'
make protocols
make[1]: Entering directory '/home/maxwellj/Development/hyprpaper'
/usr/bin/wayland-scanner private-code \
	protocols/wlr-layer-shell-unstable-v1.xml wlr-layer-shell-unstable-v1-protocol.c
/usr/bin/wayland-scanner client-header \
	protocols/wlr-layer-shell-unstable-v1.xml wlr-layer-shell-unstable-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/local/include -I/usr/include/libdrm -I/usr/include/pixman-1     -c -o wlr-layer-shell-unstable-v1-protocol.o wlr-layer-shell-unstable-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.c
/usr/bin/wayland-scanner client-header \
	//usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/local/include -I/usr/include/libdrm -I/usr/include/pixman-1     -c -o xdg-shell-protocol.o xdg-shell-protocol.c
/usr/bin/wayland-scanner private-code \
	//usr/share/wayland-protocols/staging/fractional-scale/fractional-scale-v1.xml fractional-scale-v1-protocol.c
/usr/bin/wayland-scanner client-header \
	//usr/share/wayland-protocols/staging/fractional-scale/fractional-scale-v1.xml fractional-scale-v1-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/local/include -I/usr/include/libdrm -I/usr/include/pixman-1     -c -o fractional-scale-v1-protocol.o fractional-scale-v1-protocol.c
/usr/bin/wayland-scanner private-code \
	//usr/share/wayland-protocols/stable/viewporter/viewporter.xml viewporter-protocol.c
/usr/bin/wayland-scanner client-header \
	//usr/share/wayland-protocols/stable/viewporter/viewporter.xml viewporter-protocol.h
cc -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement -I. -DWLR_USE_UNSTABLE -std=c99 -I/usr/local/include -I/usr/include/libdrm -I/usr/include/pixman-1     -c -o viewporter-protocol.o viewporter-protocol.c
make[1]: Leaving directory '/home/maxwellj/Development/hyprpaper'
make release
make[1]: Entering directory '/home/maxwellj/Development/hyprpaper'
mkdir -p build && cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -H./ -B./build -G Ninja
Not searching for unused variables given on the command line.
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring hyprpaper!
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0")
-- Checking for modules 'wayland-client;wayland-protocols;cairo;pango;pangocairo;libjpeg'
--   Found wayland-client, version 1.22.0
--   Found wayland-protocols, version 1.32
--   Found cairo, version 1.17.8
--   Found pango, version 1.50.14
--   Found pangocairo, version 1.50.14
--   Found libjpeg, version 2.1.4
-- Configuring done (1.4s)
WARNING: Preprocessor definitions containing '#' may not be passed on the compiler command line because many compilers do not support it.
CMake is dropping a preprocessor definition: GIT_COMMIT_MESSAGE="    internal: Reset hasATarget when issuing wallpaper command (#81)"
Consider defining the macro in a (configured) header file.

-- Generating done (0.0s)
-- Build files have been written to: /home/maxwellj/Development/hyprpaper/build
cmake --build ./build --config Release --target all -j 10
[2/12] Building CXX object CMakeFiles/hyprpaper.dir/src/render/WallpaperTarget.cpp.o
FAILED: CMakeFiles/hyprpaper.dir/src/render/WallpaperTarget.cpp.o
/usr/bin/c++ -DGIT_BRANCH=\"main\" -DGIT_COMMIT_HASH=\"e498c438b1e16dcf32ecb3030b20b83f7ed9ff6d\" -DGIT_DIRTY=\"\" -I/home/maxwellj/Development/hyprpaper/. -isystem /usr/include/cairo -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -isystem /usr/include/harfbuzz -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/sysprof-4 -isystem /usr/include/libxml2 -isystem /usr/include/pixman-1 -isystem /usr/include/pango-1.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/fribidi -O3 -DNDEBUG -std=c++2b -DWLR_USE_UNSTABLE -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -pthread -MD -MT CMakeFiles/hyprpaper.dir/src/render/WallpaperTarget.cpp.o -MF CMakeFiles/hyprpaper.dir/src/render/WallpaperTarget.cpp.o.d -o CMakeFiles/hyprpaper.dir/src/render/WallpaperTarget.cpp.o -c /home/maxwellj/Development/hyprpaper/src/render/WallpaperTarget.cpp
/home/maxwellj/Development/hyprpaper/src/render/WallpaperTarget.cpp:3:10: fatal error: magic.h: No such file or directory
    3 | #include <magic.h>
      |          ^~~~~~~~~
compilation terminated.
[11/12] Building CXX object CMakeFiles/hyprpaper.dir/src/Hyprpaper.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:61: release] Error 1
make[1]: Leaving directory '/home/maxwellj/Development/hyprpaper'
make: *** [Makefile:70: all] Error 2
```

**Comment by h0tc0d3** [comment]
@maxwelljens try install `file-devel` package. After installation, this error disappears.

**Comment by hmedway** [comment]
@maxwelljens @Whipplash @h0tc0d3 file-devel works on Fedora 39 (beta-frozen) to provide magic.h (/usr/include/magic.h) as well. Hyprpaper builds just fine after installation.
