### ISSUE TITLE
hyprctl hyprpaper wallpaper doesn't seem to do anything.

### ISSUE THREAD

**Issue by aditya-K2** [hyprwm/hyprpaper#39]
As mentioned in the README.
># IPC
>You can use `hyprctl hyprpaper` (if on Hyprland) to issue a keyword, for example
>```
>hyprctl hyprpaper wallpaper DP-1,~/Pictures/myepicpng.png
>```

I am running hyprpaper on a laptop (single display) and running 
```sh
$ hyprctl hyprpaper wallpaper DP-1,/D/Downloads/wallpapers/0010.jpg
```
returns `ok` but doesn't change the wallpaper. 
(keep in mind I have ran ``` hyprctl hyprpaper preload /D/Downloads/wallpapers/0010.jpg ``` before)

**Comment by thefool76** [comment]
I am also facing the same Issue today I installed hyprpaper on my single screen laptop which is running Archcraft. after using the `hyprctl hyprpaper` command but still now change I even add the paht to the image in the hyprland.conf file. but still the wallpaper won't set even after restarting several times.

**Comment by vaxerski** [comment]
can't repro; ran 
![image](https://user-images.githubusercontent.com/43317083/218097663-641b6ba6-19ef-429b-bca1-9fbcfcb14085.png)
and as expected I get anime tits on DP-3.

**Comment by thefool76** [comment]
> can't repro; ran ![image](https://user-images.githubusercontent.com/43317083/218097663-641b6ba6-19ef-429b-bca1-9fbcfcb14085.png) and as expected I get anime tits on DP-3.

worked thanks
