### ISSUE TITLE
Support for "fit"

### ISSUE THREAD

**Issue by KyleUltimate** [hyprwm/hyprpaper#6]
Currently hyprpaper would just zoom in if it doesn't fit.
![image](https://user-images.githubusercontent.com/68589851/180630373-9e10aa7e-981c-45dd-9c4a-5252460ee0ad.png)
I hope that hyprpaper can do the same thing that `sway` here.
Doesn't zoom in.

**Comment by vaxerski** [comment]
No clue what "fit" is, please use a standard name for it, as we all tend to use. See https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by KyleUltimate** [comment]
ahh, I'm sorry for the confusion. What I mean should be `contain` just by looking at the examples

**Comment by vaxerski** [comment]
added in 036bf93bf4d94e0ba6f6f95645a48d47db6ce953
