### ISSUE TITLE
How can I set wallpaper to all monitors?

### ISSUE THREAD

**Issue by 404cn** [hyprwm/hyprpaper#60]
It's like I have to write it manually in config file for every monitor?

And can I make it to use a random image in a folder like feh?

**Comment by vaxerski** [comment]
> monitor is the monitor's name, easily can be retrieved with hyprctl monitors. You can leave it empty for a wildcard (aka fallback)

```
wallpaper = ,/path/to/jpeg.jpg
```

ref: readme

> And can I make it to use a random image in a folder like feh?

```
#!/bin/zsh
randomwp=$(find /my/papers/dir/ | shuf -n 1)
echo -ne "preload=$randomwp\nwallpaper=,$randomwp"
```

**Comment by Hubro** [comment]
> ```
> wallpaper = ,/path/to/jpeg.jpg
> ```

This works for the config, but it doesn't appear to work through the IPC. This does nothing:

```
$ hyprctl hyprpaper wallpaper ",my-wallpaper.png"
```

It would be nice if this worked too. I have automatic switching between light and dark themes, and I have multiple computers with different monitor layouts so I can't hard-code the monitor names.

I can fetch all monitor names and run the IPC in a loop, but that seems like a lot of work for something that feels like very basic functionality.
