### ISSUE TITLE
Feature Request: Allow `desc` as monitor name

### ISSUE THREAD

**Issue by macearl** [hyprwm/hyprpaper#66]
If i understand correctly currently only the monitor names eDP-1, DP-1, ... are allowed to be used inside the config, while [Hyprland also allows specifying a monitor through it's description](https://wiki.hyprland.org/Configuring/Monitors/).

I often connect to different Monitors/Docking stations so that the actual monitor connected to e.g. DP-1 can have different resolutions, orientations, ...

I think it would be nice if one could utilize the description string to specify which wallpaper should be shown on which monitor.

**Comment by vaxerski** [comment]
done in 66b3ba8d9faa6b6a8894ecc03ac61667d344b8bc

**Comment by macearl** [comment]
Wow, I did not expect someone to take a look at, let alone implement this that quick.

I'll test it tomorrow

Cheers
