### ISSUE TITLE
Build dependencies in README

### ISSUE THREAD

**Issue by miscoined** [hyprwm/hyprpaper#70]
It'd be nice if the build dependencies were in the README for the manual installation. I figured it out a bit and ended up with this (just in case anyone else on OpenSUSE was having trouble):
```
sudo zypper install ninja gcc-c++ wayland-protocols-devel Mesa-libGLESv3-devel
```
Am happy to send a pull request with the change if that'd be easier for you :)

**Comment by vaxerski** [comment]
sure, feel free to pr
