### ISSUE TITLE
No initial image prevents IPC usage

### ISSUE THREAD

**Issue by kaedwen** [hyprwm/hyprpaper#74]
Hi,

I have a small golang application which prepares tmp images and tries to set them via `hyprctl hyprpaper [preload/wallpaper]`

This does not work if there is no initial preload/wallpaper specified in the static defined config. I would assume that this should also be possible.

Best regards

**Comment by andou-azarashi** [comment]
Please, read carefully. Have a line "A Wallpaper cannot be applied without preloading. The config is not reloaded dynamically." in Usage section.

**Comment by Boothwhack** [comment]
This issue has been fixed and should probably be closed.
