### ISSUE TITLE
Wallpaper can't be loaded 

### ISSUE THREAD

**Issue by Martin1134** [hyprwm/hyprpaper#75]
got the following warning

`[WARN] Monitor DP-1 does not have a target! A wallpaper will not be created.`

config:

`preload = ~/.config/Wallpapers/Nord_Night-EE80E.png

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = preload =DP-1, ~/.config/Wallpapers/Nord_Night-EE80E.png
`

**Comment by vaxerski** [comment]
```
wallpaper = preload =DP-1, ~/.config/Wallpapers/Nord_Night-EE80E.png
```
vvv
```
wallpaper = DP-1,~/.config/Wallpapers/Nord_Night-EE80E.png
```

**Comment by Martin1134** [comment]
god copy and paste error... thank you

**Comment by victorashino** [comment]
I can't make it work either

preload = ~/Pictures/Wallpapers/wpp2.png
preload = ~/Pictures/Wallpapers/wpp1.jpg

#set the default wallpaper(s) seen on initial workspace(s) --depending on >
wallpaper = eDP-1,~/Pictures/Wallpapers/wpp2.png
wallpaper = HDMI-A-1,~/Pictures/Wallpapers/wpp1.jpg

**Comment by tom-avilius** [comment]
> I can't make it work either
> 
> preload = ~/Pictures/Wallpapers/wpp2.png preload = ~/Pictures/Wallpapers/wpp1.jpg
> 
> #set the default wallpaper(s) seen on initial workspace(s) --depending on > wallpaper = eDP-1,~/Pictures/Wallpapers/wpp2.png wallpaper = HDMI-A-1,~/Pictures/Wallpapers/wpp1.jpg


can you share the log of the error you get?

**Comment by samir176520** [comment]
> ```
> wallpaper = preload =DP-1, ~/.config/Wallpapers/Nord_Night-EE80E.png
> ```
> vvv
> ```
> wallpaper = DP-1,~/.config/Wallpapers/Nord_Night-EE80E.png
> ```

Some times you should add e before DP-1 ---> eDP-1 
Thanks bro <3

**Comment by UndefinedClear** [comment]
Just make sure the file is in the correct format and—importantly—that the path to it is specified in `~/.config/hypr/hyprland.conf`.
That’s what fixed it for me; also, you can set up the `monitor =` line—just leave a space after the `=` sign, start a new line, and enter the settings.

I can't send a screenshot since I haven't set up this configuration myself yet.
