### ISSUE TITLE
Autostart with hyprland

### ISSUE THREAD

**Issue by Estebiu** [hyprwm/hyprpaper#8]
How do you actually autostart it with hyprland?
I searched around but don't seem to find the solution.

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/wiki/Advanced-config#executing

**Comment by Estebiu** [comment]
Ok, I just read the part of the wiki that mentioned it. I feel definetly stupid. 
I needed to add "exec-once=hyprpaper wallpaper eDP-1,/home/estebiu/Wallpapers/Catppuccin/buttons.png" to my hyprland.conf. People from the future, no need to thank me.

**Comment by vaxerski** [comment]
why not add that to the hyprpaper.conf?
