### ISSUE TITLE
out of memory error when reading image of wrong filetype

### ISSUE THREAD

**Issue by ItzDerock** [hyprwm/hyprpaper#80]
Not really sure if this is a bug, but the error message can definitely be a little clearer.
I accidentally saved a `.jpg` image as `.png` and when I tried to load the wallpaper I got the following error:
```
[LOG] Welcome to hyprpaper!
built from commit  ()
[CRITICAL] Failed to read image /home/derock/.config/wallpapers/020.png because of:
out of memory
```
(Image is 1.2MB and I am definitely not running into some sort of oom error)

the image: https://cdn.discordapp.com/attachments/635625973764849684/1135613164105507037/1656958851808.jpg

very simple config:
```
preload = /home/derock/.config/wallpapers/020.png
wallpaper = ,/home/derock/.config/wallpapers/020.png
ipc = off
```

running latest version from arch repos: `hyprpaper 0.3.0-1`

if possible, maybe make the error say something like invalid image, would've saved me some time trying to figure out why my wallpaper wasn't loading. (maybe check the magic bytes?)

**Comment by vaxerski** [comment]
https://github.com/hyprwm/hyprpaper/blob/9261356bd74fadbc544bec22c16aec62ebba13bd/src/render/WallpaperTarget.cpp#L41

reason is taken from cairo, idk what else you want me to do here.

**Comment by ItzDerock** [comment]
ah i see, in that case we can just close this.
