### ISSUE TITLE
`hyprctl hyprpaper wallpaper` doesn't change wallpaper

### ISSUE THREAD

**Issue by loqusion** [hyprwm/hyprpaper#84]
When I run the following:

```sh
hyprctl hyprpaper wallpaper "DP-3,~/Pictures/Wallpapers/Judo.png"
```

I get `unknown request` and the wallpaper doesn't change. Hyprpaper otherwise functions normally.

## Version info

Hyprland: `r3198.3f7f4207-1`
Hyprpaper: `r108.e498c43-1`

**Comment by shadeyg56** [comment]
I am experiencing this as well.

**Comment by shadeyg56** [comment]
Also I am on v0.3.0 of hyprpaper but I am built from the latest commit of Hyprland so I believe this is an issue with new updates to Hyprland not hyprpaper

**Comment by shadeyg56** [comment]
I went ahead and made an issue in the hyprland repo at hyprwm/hyprland#2947

**Comment by loqusion** [comment]
I'll go ahead and close the issue, it's working for me now.
