### ISSUE TITLE
Do not critically exit if config file does not exist

### ISSUE THREAD

**Issue by Vinetos** [hyprwm/hyprpaper#87]
Nowadays, most of wallpaper utilities allow the user to run them without a configuration file. 

Actually, If we run `hyprpaper` without a config file, we have :
```shell
[LOG] Welcome to hyprpaper!
built from commit v0.4.0 ()
[CRITICAL] Config file `/home/vinetos/.config/hypr/hyprpaper.conf` couldn't be opened.
```

What I would like to have is : 
Running `hyprpaper` -> Starts the deamon
Then manually preload, change and unload wallpapers from the command line.

Is it a behavior that you (maintainers) want to allow ? 

One way to allows this with :
```cpp
if (!ifs.good()) {
        Debug::log(WARN, "Config file `%s` couldn't be opened.", configPath.c_str());
        return;
    }
```

But it will leads to `[WARN] Monitor eDP-1 does not have a target! A wallpaper will not be created.`. Is this a problem ?

**Comment by zjhendryx** [comment]
I utilize hyprpaper similar to you, in that I run the deamon and then I have a separate application that sets my original wallpaper for each monitor but then changes them based on what apps I'm running and what workspace I'm on.
Currently I run with just a blank empty file in that location to allow hyprpaper to run, and have no experienced any issues.

**Comment by vaxerski** [comment]
running hyprpaper with an empty config is fine, error is back from the no-ipc days I think. We can remove this and just make it a warning

**Comment by vaxerski** [comment]
with the move to hyprlang this needs to be first implemented there. https://github.com/hyprwm/hyprlang
